#!/bin/bash

tempDir=tomcat$(date)
cd tempDir
wget -O tomcat.tar.gz http://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-9/v9.0.16/bin/apache-tomcat-9.0.16.tar.gz
if test $? != 0; then
    echo '下载失败'
    exit
fi
tar -zxvf tomcat.tar.gz 
