#!/bin/bash

if test ! -d ~/softInstall/node10.15;then
	mkdir -p ~/softInstall/node10.15
fi
cd ~/softInstall/node10.15
mkdir targzTemp; cd targzTemp
wget -O node.tar.xz https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.xz
tar -xJvf node.tar.xz -C ../ --strip-components=1
if test $? != 0; then
	echo '解压失败,重试'
	cd ../; rm -rf targzTemp
	exit
fi
cd ../
rm -rf targzTemp
path=$(pwd)
installPath=/opt/node
if test ! -d $installPath; then
	sudo mkdir -p $installPath
fi
sudo ln -s $path $installPath/node10.15 
if test ! -f ~/.bashrc.node.cp; then
	cp ~/.bashrc ~/.bashrc.node.cp
	cp ~/.bashrc $path/.bashrc.cp
	echo 'cp .bashrc success ==> .bashrc.node.cp'
else
	rm -rf ~/.bashrc
	cp ~/.bashrc.node.cp ~/.bashrc
fi
cat <<EOF >> ~/.bashrc
export NODE_HOME=${installPath}/node10.15
export PATH=\${NODE_HOME}/bin:\$PATH
EOF
if test $? != 0; then
	rm -rf ~/.bashrc
	mv ~/.bashrc.node.cp .bashrc
	echo '写于环境变量失败 .bashrc'
	exit
fi
#sudo ln -s ${installPath}/node10.15/bin/node /usr/bin/node
#sudo ln -s ${installPath}/node10.15/bin/npm /usr/bin/npm
#sudo ln -s ${installPath}/node10.15/bin/npx /usr/bin/npx

